application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "yyxwyutsrqponmlkjihg"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "yarbac"
  require_ssl: false